server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true #To beautify or pretty print the SQL
        default_batch_fetch_size: 1000

    show-sql: true  # show sql

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

logging:
  level:
    org.hibernate.type: debug #show parameter binding
    SQL: debug

